spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&charaEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


  logging:
    level:
      root: wran
      com.yc.blogs: debug
    file: ./log/blog-pro.log
server:
  port: 8085
